---
### provision AWS EC2 UI instance
- hosts: ui
  gather_facts: false
  become: yes
  # become_user: ubuntu
  # pre_tasks:
  #   - include_vars: variables.yml
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install npm and git
      apt:
        pkg:
          - npm
          - git

    - name: clone repository
      git:
        repo: https://github.com/gaearaz/movie-analyst-ui.git
        dest: /home/ubuntu/ui
        clone: yes

    - name: execute npm install command
      npm:
        path: /home/ubuntu/ui

    - name: execute npm run command using shell
      shell: node /home/ubuntu/ui/server.js

### provision AWS EC2 API instance
- hosts: api
  gather_facts: false
  become: yes

  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install npm and git
      apt:
        pkg:
          - npm
          - git

    - name: clone repository
      git:
        repo: https://github.com/gaearaz/movie-analyst-api.git
        dest: /home/ubuntu/api
        clone: yes

    - name: execute npm install command
      npm:
        path: /home/ubuntu/api

    - name: execute npm run command using shell
      shell: node /home/ubuntu/api/server.js
