---
### provision AWS EC2 UI instance
- hosts: ui
  gather_facts: false
  become: yes
  # become_user: ubuntu
  # pre_tasks:
  #   - include_vars: variables.yml
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install npm and git
      apt:
        pkg:
          - npm
          - git

    - name: clone repository
      git:
        repo: https://github.com/gaearaz/movie-analyst-ui.git
        dest: /home/ubuntu/ui
        clone: yes

    - name: replace env variable backhost
      shell: sed -i 's/localhost/172.31.37.30/g' /home/ubuntu/ui/.env

    - name: execute npm install command
      npm:
        path: /home/ubuntu/ui

    - name: execute npm run command using shell
      # shell: nohup node /home/ubuntu/ui/server.js >> app.log 2>&1 &
      # shell: node /home/ubuntu/ui/server.js
      shell: pm2 start /home/ubuntu/ui/server.js
